version: 2
jobs:
  build:
    docker:
      - image: node:7
    working_directory: /home/ubuntu/circleci-2.0-sandbox
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: sample
          command: docker run -t node:7 node -v
